export const baseHeavyBodyAcrylicPaints = [
   {red: 77, green: 33, blue: 33, name: 'Liquitex: Alizarin Crimson Hue Permanent'},
   {red: 63, green: 55, blue: 48, name: 'Liquitex: Raw Umber'},
   {red: 220, green: 208, blue: 33, name: 'Liquitex: Yellow Light Hansa'},
   {red: 201, green: 31, blue: 27, name: 'Liquitex: Cadmium Red Medium'},
   {red: 213, green: 214, blue: 207, name: 'Liquitex: Parchment'},
   {red: 16, green: 145, blue: 139, name: 'Liquitex: Bright Aqua Green'},
   {red: 10, green: 113, blue: 180, name: 'Liquitex: Brilliant Blue'},
   {red: 121, green: 101, blue: 191, name: 'Liquitex: Brilliant Purple'},
   {red: 141, green: 190, blue: 49, name: 'Liquitex: Brilliant Yellow Green'},
   {red: 141, green: 105, blue: 44, name: 'Liquitex: Bronze Yellow'},
   {red: 112, green: 56, blue: 41, name: 'Liquitex: Burnt Sienna'},
   {red: 61, green: 44, blue: 38, name: 'Liquitex: Burnt Umber'},
   {red: 252, green: 124, blue: 50, name: 'Liquitex: Cadmium Orange'},
   {red: 231, green: 119, blue: 0, name: 'Liquitex: Cadmium Orange Hue'},
   {red: 148, green: 33, blue: 35, name: 'Liquitex: Cadmium Red Deep Hue'},
   {red: 240, green: 70, blue: 51, name: 'Liquitex: Cadmium Red Light'},
   {red: 237, green: 64, blue: 49, name: 'Liquitex: Cadmium Red Light Hue'},
   {red: 183, green: 33, blue: 32, name: 'Liquitex: Cadmium Red Medium Hue'},
   {red: 234, green: 150, blue: 1, name: 'Liquitex: Cadmium Yellow Deep Hue'},
   {red: 244, green: 184, blue: 1, name: 'Liquitex: Cadmium Yellow Medium'},
   {red: 228, green: 167, blue: 1, name: 'Liquitex: Cadmium Yellow Medium Hue'},
   {red: 254, green: 244, blue: 61, name: 'Liquitex: Cadmium Yellow Light'},
   {red: 252, green: 244, blue: 55, name: 'Liquitex: Cadmium Yellow Light Hue'},
   {red: 29, green: 101, blue: 174, name: 'Liquitex: Cerulean Blue Hue'},
   {red: 27, green: 95, blue: 164, name: 'Liquitex; Cerulean Blue'},
   {red: 17, green: 118, blue: 59, name: 'Liquitex: Chromium Oxide Green'},
   {red: 33, green: 60, blue: 161, name: 'Liquitex: Cobalt Blue Hue'},
   {red: 0, green: 96, blue: 169, name: 'Liquitex: Cobalt Blue'},
   {red: 14, green: 98, blue: 92, name: 'Liquitex: Cobalt Green'},
   {red: 0, green: 161, blue: 171, name: 'Liquitex: Cobalt Teal'},
   {red: 7, green: 106, blue: 109, name: 'Liquitex: Cobalt Turquiose'},
   {red: 111, green: 24, blue: 49, name: 'Liquitex: Deep Magenta'},
   {red: 25, green: 13, blue: 15, name: 'Liquitex: Deep Violet'},
   {red: 17, green: 17, blue: 17, name: 'Liquitex: Dioxazine Purple'},
   {red: 10, green: 119, blue: 73, name: 'Liquitex: Emerald Green'},
   {red: 3, green: 37, blue: 23, name: 'Liquitex: Deep Green Permanent'},
   {red: 112, green: 106, blue: 0, name: 'Liquitex: Green Gold'},
   {red: 5, green: 30, blue: 11, name: 'Liquitex: Hooker\'s Green Hue Permanent'},
   {red: 9, green: 9, blue: 9, name: 'Liquitex: Hooker\'s Green Deep Hue Permanent'},
   {red: 229, green: 139, blue: 21, name: 'Liquitex: Indian Yellow'},
   {red: 8, green: 5, blue: 6, name: 'Liquitex: Indanthrene Blue'},
   {red: 168, green: 139, blue: 79, name: 'Liquitex: Iridescent Antique Gold'},
   {red: 194, green: 151, blue: 9, name: 'Liquitex: Iridescent Bright Gold'},
   {red: 170, green: 170, blue: 170, name: 'Liquitex: Iridescent Bright Silver'},
   {red: 114, green: 70, blue: 43, name: 'Liquitex: Iridescent Rich Bronze'},
   {red: 155, green: 70, blue: 8, name: 'Liquitex: Iridescent Rich Copper'},
   {red: 186, green: 151, blue: 57, name: 'Liquitex: Iridescent Rich Gold'},
   {red: 110, green: 110, blue: 110, name: 'Liquitex: Iridescent Rich Silver'},
   {red: 185, green: 185, blue: 185, name: 'Liquitex: Iridescent White'},
   {red: 0, green: 0, blue: 0, name: 'Liquitex: Ivory Black'},
   {red: 75, green: 197, blue: 240, name: 'Liquitex: Light Blue Permanent'},
   {red: 101, green: 150, blue: 235, name: 'Liquitex: Light Blue Violet'},
   {red: 61, green: 185, blue: 87, name: 'Liquitex: Light Emerald Green'},
   {red: 17, green: 152, blue: 68, name: 'Liquitex: Light Green Permanent'},
   {red: 254, green: 200, blue: 198, name: 'Liquitex: Light Portrait Pink'},
   {red: 0, green: 0, blue: 0, name: 'Liquitex: Mars Black'},
   {red: 16, green: 77, blue: 144, name: 'Liquitex: Manganese Blue Hue'},
   {red: 211, green: 85, blue: 155, name: 'Liquitex: Medium Magenta'},
   {red: 188, green: 32, blue: 36, name: 'Liquitex; Naphthol Crimson'},
   {red: 219, green: 40, blue: 33, name: 'Liquitex: Naphthol Red Light'},
   {red: 145, green: 145, blue: 159, name: 'Liquitex: Neutral Gray 5'},
   {red: 19, green: 42, blue: 53, name: 'Liquitex: Payne\'s Gray'},
   {red: 123, green: 38, blue: 35, name: 'Liquitex: Pyrrole Crimson'},
   {red: 102, green: 28, blue: 26, name: 'Liquitex: Quinacridone Red Orange'},
   {red: 164, green: 32, blue: 40, name: 'Liquitex: Quinacridone Red'},
   {red: 253, green: 192, blue: 102, name: 'Liquitex: Naples Yellow Hue'},
   {red: 14, green: 7, blue: 52, name: 'Liquitex: Phthalo Blue (Green Shade)'},
   {red: 24, green: 17, blue: 58, name: 'Liquitex: Phthalo Blue (Red Shade)'},
   {red: 7, green: 7, blue: 9, name: 'Liquitex: Prussian Blue Hue'},
   {red: 11, green: 11, blue: 11, name: 'Liquitex: Phthalo Green (Blue Shade)'},
   {red: 17, green: 34, blue: 30, name: 'Liquitex: Phthalo Green (Yellow Shade)'},
   {red: 15, green: 12, blue: 15, name: 'Liquitex: Prism Violet'},
   {red: 255, green: 82, blue: 64, name: 'Liquitex: Pyrrole Orange'},
   {red: 152, green: 16, blue: 14, name: 'Liquitex: Pyrrole Red'},
   {red: 49, green: 29, blue: 31, name: 'Liquitex: Quinacridone Blue Violet'},
   {red: 58, green: 30, blue: 27, name: 'Liquitex: Quinacridone Burnt Orange'},
   {red: 113, green: 29, blue: 44, name: 'Liquitex: Quinacridone Magenta'},
   {red: 95, green: 48, blue: 16, name: 'Liquitex: Raw Sienna'},
   {red: 130, green: 44, blue: 22, name: 'Liquitex: Red Oxide'},
   {red: 48, green: 51, blue: 48, name: 'Liquitex: Sap Green Permanent'},
   {red: 255, green: 255, blue: 255, name: 'Liquitex: Titanium White'},
   {red: 72, green: 30, blue: 20, name: 'Liquitex: Transparent Burnt Sienna'},
   {red: 20, green: 20, blue: 20, name: 'Liquitex: Transparent Burnt Umber'},
   {red: 255, green: 255, blue: 255, name: 'Liquitex: Transparent Mixing White'},
   {red: 94, green: 58, blue: 17, name: 'Liquitex: Transparent Raw Sienna'},
   {red: 13, green: 13, blue: 13, name: 'Liquitex: Transparent Raw Umber'},
   {red: 4, green: 7, blue: 6, name: 'Liquitex: Transparent Viridian Hue'},
   {red: 225, green: 166, blue: 33, name: 'Liquitex: Turner\'s Yellow'},
   {red: 28, green: 26, blue: 37, name: 'Liquitex: Turquoise Deep'},
   {red: 177, green: 155, blue: 123, name: 'Liquitex: Unbleached Titanium'},
   {red: 18, green: 17, blue: 56, name: 'Liquitex: Ultramarine Blue (Green Shade)'},
   {red: 34, green: 31, blue: 61, name: 'Liquitex: Ultramarine Blue (Red Shade)'},
   {red: 53, green: 32, blue: 23, name: 'Liquitex: Van Dyke Red'},
   {red: 85, green: 151, blue: 22, name: 'Liquitex: Vivid Lime Green'},
   {red: 26, green: 26, blue: 26, name: 'Liquitex: Viridian Hue Permanent'},
   {red: 218, green: 163, blue: 1, name: 'Liquitex: Yellow Medium Azo'},
   {red: 226, green: 135, blue: 0, name: 'Liquitex: Yellow Orange Azo'},
   {red: 172, green: 120, blue: 30, name: 'Liquitex: Yellow Oxide'},
   {red: 38, green: 6, blue: 8, name: 'Golden: Alizarin Crimson Historic Hue'},
   {red: 8, green: 5, blue: 6, name: 'Golden: Anthraquinone Blue'},
   {red: 225, green: 170, blue: 23, name: 'Golden: Aureolin Historic Hue'},
   {red: 36, green: 43, blue: 58, name: 'Golden: Azurite Historic Hue'},
   {red: 243, green: 216, blue: 2, name: 'Golden: Bismuth Vanadate Yellow'},
   {red: 78, green: 38, blue: 30, name: 'Golden: Burnt Sienna'},
   {red: 50, green: 37, blue: 31, name: 'Golden: Burnt Umber'},
   {red: 61, green: 36, blue: 29, name: 'Golden: Burnt Umber Light'},
   {red: 249, green: 100, blue: 51, name: 'Golden: Cadmium Orange (CP)'},
   {red: 164, green: 42, blue: 45, name: 'Golden: Cadmium Red Dark (CP)'},
   {red: 236, green: 68, blue: 54, name: 'Golden: Cadmium Red Light (CP)'},
   {red: 159, green: 20, blue: 22, name: 'Golden: Cadmium Red Medium (CP)'},
   {red: 179, green: 30, blue: 31, name: 'Golden: Cadmium Red Medium Hue'},
   {red: 254, green: 201, blue: 73, name: 'Golden: Cadmium Yellow Dark (CP)'},
   {red: 254, green: 246, blue: 51, name: 'Golden: Cadmium Yellow Light (CP)'},
   {red: 237, green: 180, blue: 1, name: 'Golden: Cadmium Yellow Medium (CP)'},
   {red: 255, green: 247, blue: 76, name: 'Golden: Cadmium Yellow Primrose (CP)'},
   {red: 16, green: 62, blue: 122, name: 'Golden: Cerulean Blue Chromium'},
   {red: 18, green: 59, blue: 89, name: 'Golden: Cerulean Blue Deep'},
   {red: 60, green: 106, blue: 48, name: 'Golden: Chromium Oxide Green'},
   {red: 43, green: 58, blue: 34, name: 'Golden: Chromium Oxide Green Dark'},
   {red: 21, green: 41, blue: 134, name: 'Golden: Cobalt Blue'},
   {red: 20, green: 44, blue: 139, name: 'Golden: Cobalt Blue Hue'},
   {red: 15, green: 67, blue: 52, name: 'Golden: Cobalt Green'},
   {red: 10, green: 92, blue: 103, name: 'Golden: Cobalt Turquoise'},
   {red: 76, green: 25, blue: 45, name: 'Golden: Cobalt Violet Historic Hue'},
   {red: 234, green: 146, blue: 0, name: 'Golden: Diarylide Yellow'},
   {red: 37, green: 27, blue: 27, name: 'Golden: Dioxazine Purple'},
   {red: 72, green: 69, blue: 64, name: 'Golden: Graphite Gray'},
   {red: 61, green: 81, blue: 10, name: 'Golden: Green Gold'},
   {red: 236, green: 204, blue: 1, name: 'Golden: Hansa Yellow Light'},
   {red: 228, green: 170, blue: 1, name: 'Golden: Hansa Yellow Medium'},
   {red: 233, green: 185, blue: 0, name: 'Golden: Hansa Yellow Opaque'},
   {red: 9, green: 9, blue: 9, name: 'Golden: Hooker\'s Green Historic Hue'},
   {red: 187, green: 107, blue: 6, name: 'Golden: Indian Yellow Historic Hue'},
   {red: 7, green: 7, blue: 7, name: 'Golden: Jenkins Green'},
   {red: 33, green: 155, blue: 46, name: 'Golden: Light Green (Blue Shade)'},
   {red: 85, green: 167, blue: 41, name: 'Golden: Light Green (Yellow Shade)'},
   {red: 208, green: 117, blue: 127, name: 'Golden: Light Magenta'},
   {red: 0, green: 124, blue: 115, name: 'Golden: Light Turquiose (Phthalo'},
   {red: 80, green: 118, blue: 197, name: 'Golden: Light Ultamarine Blue'},
   {red: 85, green: 61, blue: 131, name: 'Golden: Light Violet'},
   {red: 1, green: 47, blue: 107, name: 'Golden: Manganese Blue Historic Hue'},
   {red: 143, green: 67, blue: 36, name: 'Golden: Mars Yellow'},
   {red: 172, green: 49, blue: 104, name: 'Golden: Medium Magenta'},
   {red: 78, green: 42, blue: 110, name: 'Golden: Medium Violet'},
   {red: 205, green: 34, blue: 28, name: 'Golden: Naphthol Red Light'},
   {red: 141, green: 27, blue: 33, name: 'Golden: Naphthol Red Medium'},
   {red: 183, green: 144, blue: 69, name: 'Golden: Naples Yellow Historic Hue'},
   {red: 47, green: 47, blue: 47, name: 'Golden: Neutral Gray N2'},
   {red: 42, green: 42, blue: 42, name: 'Golden: Neutral Gray N3'},
   {red: 92, green: 92, blue: 92, name: 'Golden: Neutral Gray N4'},
   {red: 116, green: 116, blue: 116, name: 'Golden: Neutral Gray N5'},
   {red: 143, green: 143, blue: 143, name: 'Golden: Neutral Gray N6'},
   {red: 180, green: 180, blue: 180, name: 'Golden: Neutral Gray N7'},
   {red: 199, green: 199, blue: 199, name: 'Golden: Neutral Gray N8'},
   {red: 127, green: 83, blue: 5, name: 'Golden: Nickel Azo Yellow'},
   {red: 24, green: 24, blue: 24, name: 'Golden: Paynes Gray'},
   {red: 0, green: 95, blue: 44, name: 'Golden: Permanent Green Light'},
   {red: 40, green: 24, blue: 25, name: 'Golden: Permanent Maroon'},
   {red: 41, green: 25, blue: 31, name: 'Golden: Permanent Violet Dark'},
   {red: 26, green: 19, blue: 51, name: 'Golden: Phthalo Blue (Green Shade)'},
   {red: 21, green: 16, blue: 33, name: 'Golden: Phthalo Blue (Red Shade)'},
   {red: 26, green: 36, blue: 38, name: 'Golden: Phthalo Green (Blue Shade)'},
   {red: 1, green: 8, blue: 6, name: 'Golden: Phthalo Green (Yellow Shade)'},
   {red: 11, green: 40, blue: 97, name: 'Golden: Primary Cyan'},
   {red: 233, green: 190, blue: 0, name: 'Golden: Primary Yellow'},
   {red: 6, green: 6, blue: 8, name: 'Golden: Prussian Blue Historic Hue'},
   {red: 242, green: 65, blue: 43, name: 'Golden: Pyrrole Orange'},
   {red: 183, green: 19, blue: 23, name: 'Golden: Pyrrole Red'},
   {red: 186, green: 37, blue: 42, name: 'Golden: Pyrrole Red Dark'},
   {red: 194, green: 38, blue: 27, name: 'Golden: Red Light'},
   {red: 52, green: 22, blue: 19, name: 'Golden: Quinacridone Burnt Orange'},
   {red: 68, green: 16, blue: 20, name: 'Golden: Quinacridone Crimson'},
   {red: 74, green: 17, blue: 23, name: 'Golden: Quinacridone Magenta'},
   {red: 139, green: 19, blue: 23, name: 'Golden: Quinacridone Red'},
   {red: 167, green: 41, blue: 48, name: 'Golden: Quinacridone Red Light'},
   {red: 84, green: 16, blue: 20, name: 'Golden: Quinacridone Violet'},
   {red: 86, green: 31, blue: 18, name: 'Golden: Quinacridone Nickel Azo Gold'},
   {red: 127, green: 73, blue: 23, name: 'Golden: Raw Sienna'},
   {red: 41, green: 41, blue: 41, name: 'Golden: Raw Umber'},
   {red: 117, green: 39, blue: 24, name: 'Golden: Red Oxide'},
   {red: 7, green: 7, blue: 7, name: 'Golden: Sap Green Historic Hue'},
   {red: 38, green: 36, blue: 41, name: 'Golden: Smalt Historic Hue'},
   {red: 8, green: 132, blue: 146, name: 'Golden: Teal'},
   {red: 42, green: 47, blue: 35, name: 'Golden: Terre Verte Historic Hue'},
   {red: 189, green: 173, blue: 148, name: 'Golden: Titan Buff'},
   {red: 254, green: 248, blue: 142, name: 'Golden: Titanate Yellow'},
   {red: 51, green: 36, blue: 31, name: 'Golden: Transparent Brown Iron Oxide'},
   {red: 174, green: 39, blue: 31, name: 'Golden: Transparent Pyrrole Orange'},
   {red: 63, green: 23, blue: 15, name: 'Golden: Transparent Red Iron Oxide'},
   {red: 169, green: 91, blue: 21, name: 'Golden: Transparent Yellow Iron Oxide'},
   {red: 7, green: 5, blue: 15, name: 'Golden: Turquois (Phthalo)'},
   {red: 28, green: 24, blue: 64, name: 'Golden: Ultramarine Blue'},
   {red: 13, green: 8, blue: 36, name: 'Golden: Ultramarine Violet'},
   {red: 31, green: 26, blue: 22, name: 'Golden: Van Dyke Brown Historic Hue'},
   {red: 209, green: 62, blue: 7, name: 'Golden: Vat Orange'},
   {red: 72, green: 22, blue: 16, name: 'Golden: Violet Oxide'},
   {red: 36, green: 58, blue: 51, name: 'Golden: Viridian Green Hue'},
   {red: 136, green: 84, blue: 24, name: 'Golden: Yellow Ochre'},
   {red: 179, green: 124, blue: 30, name: 'Golden: Yellow Oxide'},
   {red: 232, green: 89, blue: 28, name: 'Liquitex: Vivid Red Orange'},
   {red: 146, green: 24, blue: 29, name: 'Liquitex: Quinacridone Crimson'},
   {red: 253, green: 216, blue: 71, name: 'Golden: Cadmium Yellow Medium Hue'},
   {red: 224, green: 42, blue: 44, name: 'Liquitex: Cadmium Red Medium'},
];

export const halfWhiteHeavyBodyAcrylicPaints = [
   {red: 210, green: 186, blue: 31, name: 'Liquitex: Cadmium Yellow Light (Half-White)'},
   {red: 197, green: 176, blue: 45, name: 'Liquitex: Cadmium Yellow Light Hue (Half-White)'},
   {red: 35, green: 101, blue: 153, name: 'Liquitex: Cerulean Blue Hue (Half-White)'},
   {red: 98, green: 139, blue: 189, name: 'Liquitex; Cerulean Blue (Half-White)'},
   {red: 79, green: 103, blue: 67, name: 'Liquitex: Chromium Oxide Green (Half-White)'},
   {red: 50, green: 95, blue: 179, name: 'Liquitex: Cobalt Blue Hue (Half-White)'},
   {red: 77, green: 116, blue: 176, name: 'Liquitex: Cobalt Blue (Half-White)'},
   {red: 50, green: 112, blue: 113, name: 'Liquitex: Cobalt Green (Half-White)'},
   {red: 104, green: 168, blue: 190, name: 'Liquitex: Cobalt Teal (Half-White)'},
   {red: 78, green: 133, blue: 143, name: 'Liquitex: Cobalt Turquiose (Half-White)'},
   {red: 154, green: 74, blue: 119, name: 'Liquitex: Deep Magenta (Half-White)'},
   {red: 120, green: 89, blue: 119, name: 'Liquitex: Deep Violet (Half-White)'},
   {red: 78, green: 49, blue: 126, name: 'Liquitex: Dioxazine Purple (Half-White)'},
   {red: 58, green: 151, blue: 109, name: 'Liquitex: Emerald Green (Half-White)'},
   {red: 14, green: 129, blue: 86, name: 'Liquitex: Deep Green Permanent (Half-White)'},
   {red: 155, green: 138, blue: 23, name: 'Liquitex: Green Gold (Half-White)'},
   {red: 69, green: 120, blue: 73, name: 'Liquitex: Hooker\'s Green Hue Permanent (Half-White)'},
   {red: 60, green: 78, blue: 74, name: 'Liquitex: Hooker\'s Green Deep Hue Permanent (Half-White)'},
   {red: 202, green: 145, blue: 13, name: 'Liquitex: Indian Yellow (Half-White)'},
   {red: 29, green: 59, blue: 109, name: 'Liquitex: Indanthrene Blue (Half-White)'},
   {red: 175, green: 166, blue: 159, name: 'Liquitex: Iridescent Antique Gold (Half-White)'},
   {red: 206, green: 186, blue: 168, name: 'Liquitex: Iridescent Bright Gold (Half-White)'},
   {red: 179, green: 175, blue: 173, name: 'Liquitex: Iridescent Bright Silver (Half-White)'},
   {red: 120, green: 103, blue: 99, name: 'Liquitex: Iridescent Rich Bronze (Half-White)'},
   {red: 158, green: 141, blue: 141, name: 'Liquitex: Iridescent Rich Copper (Half-White)'},
   {red: 206, green: 189, blue: 174, name: 'Liquitex: Iridescent Rich Gold (Half-White)'},
   {red: 181, green: 179, blue: 178, name: 'Liquitex: Iridescent Rich Silver (Half-White)'},
   {red: 206, green: 201, blue: 197, name: 'Liquitex: Iridescent White (Half-White)'},
   {red: 0, green: 0, blue: 0, name: 'Liquitex: Ivory Black (Half-White)'},
   {red: 100, green: 157, blue: 189, name: 'Liquitex: Light Blue Permanent (Half-White)'},
   {red: 119, green: 144, blue: 203, name: 'Liquitex: Light Blue Violet (Half-White)'},
   {red: 120, green: 176, blue: 117, name: 'Liquitex: Light Emerald Green (Half-White)'},
   {red: 91, green: 161, blue: 101, name: 'Liquitex: Light Green Permanent (Half-White)'},
   {red: 195, green: 149, blue: 137, name: 'Liquitex: Light Portrait Pink (Half-White)'},
   {red: 43, green: 44, blue: 48, name: 'Liquitex: Mars Black (Half-White)'},
   {red: 3, green: 88, blue: 156, name: 'Liquitex: Manganese Blue Hue (Half-White)'},
   {red: 184, green: 109, blue: 145, name: 'Liquitex: Medium Magenta (Half-White)'},
   {red: 186, green: 66, blue: 90, name: 'Liquitex; Naphthol Crimson (Half-White)'},
   {red: 189, green: 61, blue: 62, name: 'Liquitex: Naphthol Red Light (Half-White)'},
   {red: 107, green: 108, blue: 105, name: 'Liquitex: Neutral Gray 5 (Half-White)'},
   {red: 89, green: 98, blue: 110, name: 'Liquitex: Payne\'s Gray (Half-White)'},
   {red: 180, green: 58, blue: 77, name: 'Liquitex: Pyrrole Crimson (Half-White)'},
   {red: 185, green: 61, blue: 57, name: 'Liquitex: Quinacridone Red Orange (Half-White)'},
   {red: 205, green: 99, blue: 110, name: 'Liquitex: Quinacridone Red (Half-White)'},
   {red: 198, green: 156, blue: 90, name: 'Liquitex: Naples Yellow Hue (Half-White)'},
   {red: 1, green: 76, blue: 146, name: 'Liquitex: Phthalo Blue (Green Shade) (Half-White)'},
   {red: 25, green: 80, blue: 161, name: 'Liquitex: Phthalo Blue (Red Shade) (Half-White)'},
   {red: 46, green: 84, blue: 125, name: 'Liquitex: Prussian Blue Hue (Half-White)'},
   {red: 14, green: 147, blue: 131, name: 'Liquitex: Phthalo Green (Blue Shade) (Half-White)'},
];
